-- Seed data for BillFlow Demo
-- This script populates the database with a usable demo account, clients, and invoices.
-- Note: 'password_hash' is a placeholder. You will need to replace it with a valid hash (e.g., of 'password123') generated by your FastAPI auth setup.

-- 1. Create a demo user
INSERT INTO users (id, email, password_hash, created_at, updated_at) 
VALUES (
    '11111111-1111-1111-1111-111111111111', 
    'demo@billflow.com', 
    '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPIzFzwb2', -- Example bcrypt hash for 'password123'
    NOW(), 
    NOW()
);

-- 2. Create business settings for the demo user
INSERT INTO business_settings (id, user_id, business_name, logo_url, currency, invoice_number_prefix, created_at, updated_at) 
VALUES (
    '22222222-2222-2222-2222-222222222222', 
    '11111111-1111-1111-1111-111111111111', 
    'Demo Freelance Studio', 
    'https://via.placeholder.com/150', 
    'USD', 
    'DEMO-', 
    NOW(), 
    NOW()
);

-- 3. Create sample clients
INSERT INTO clients (id, user_id, name, email, company, address, phone, created_at, updated_at) 
VALUES 
    (
        '33333333-3333-3333-3333-333333333331', 
        '11111111-1111-1111-1111-111111111111', 
        'Alice Cooper', 
        'alice@exampleclient.com', 
        'Alice Design Co.', 
        '123 Design St, Seattle, WA', 
        '555-0101', 
        NOW(), 
        NOW()
    ),
    (
        '33333333-3333-3333-3333-333333333332', 
        '11111111-1111-1111-1111-111111111111', 
        'Bob Jones', 
        'bob@jonesllc.com', 
        'Jones Tech LLC', 
        '456 Tech Blvd, Austin, TX', 
        '555-0202', 
        NOW(), 
        NOW()
    );

-- 4. Create sample invoices (One sent/unpaid, one paid)
INSERT INTO invoices (id, user_id, client_id, invoice_number, issue_date, due_date, notes, status, subtotal, tax, discount, total, public_token, created_at, updated_at) 
VALUES 
    -- Invoice 1: Sent (Unpaid, due in 10 days)
    (
        '44444444-4444-4444-4444-444444444441', 
        '11111111-1111-1111-1111-111111111111', 
        '33333333-3333-3333-3333-333333333331', 
        'DEMO-001', 
        CURRENT_DATE - INTERVAL '5 days', 
        CURRENT_DATE + INTERVAL '10 days', 
        'Thank you for your business!', 
        'sent', 
        1500.00, 
        0.00, 
        0.00, 
        1500.00, 
        'pub_token_abc123xyz890', 
        NOW(), 
        NOW()
    ),
    -- Invoice 2: Paid
    (
        '44444444-4444-4444-4444-444444444442', 
        '11111111-1111-1111-1111-111111111111', 
        '33333333-3333-3333-3333-333333333332', 
        'DEMO-002', 
        CURRENT_DATE - INTERVAL '20 days', 
        CURRENT_DATE - INTERVAL '5 days', 
        'Payment received in full. Pleasure working with you.', 
        'paid', 
        2500.00, 
        250.00, 
        100.00, 
        2650.00, 
        'pub_token_def456uvw123', 
        NOW(), 
        NOW()
    );

-- 5. Create invoice line items
INSERT INTO invoice_items (id, invoice_id, description, quantity, rate, line_total, created_at) 
VALUES 
    -- Items for Invoice 1
    (
        '55555555-5555-5555-5555-555555555551', 
        '44444444-4444-4444-4444-444444444441', 
        'Website Redesign - Wireframes', 
        10.00, 
        100.00, 
        1000.00, 
        NOW()
    ),
    (
        '55555555-5555-5555-5555-555555555552', 
        '44444444-4444-4444-4444-444444444441', 
        'Logo Concepts', 
        10.00, 
        50.00, 
        500.00, 
        NOW()
    ),
    -- Items for Invoice 2
    (
        '55555555-5555-5555-5555-555555555553', 
        '44444444-4444-4444-4444-444444444442', 
        'Backend API Development (Hours)', 
        20.00, 
        125.00, 
        2500.00, 
        NOW()
    );
